      - name: Setup & Build
        run: |
          # 1. 安装依赖
          sudo apt update
          sudo apt install -y bc build-essential flex bison libssl-dev libelf-dev \
          clang lld llvm gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libncurses5

          # 2. 修复源码 Bug (重点：纠正错误的头文件引用)
          echo "---- 正在修复 tspdrv 源码 Bug ----"
          sed -i 's/<sys\/ioctl.h>/<linux\/ioctl.h>/g' include/uapi/linux/tspdrv.h

          # 3. 设置变量
          export ARCH=arm64
          export SUBARCH=arm64
          
          MAKE_ARGS="
            O=out \
            ARCH=arm64 \
            CC=clang \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            HOSTCC=gcc \
            HOSTCXX=g++
          "

          # 4. 开始执行
          echo "---- 正在生成配置文件 ----"
          make $MAKE_ARGS lineageos_joan_defconfig

          echo "---- 正在开始编译 ----"
          make -j$(nproc) $MAKE_ARGS
